spring:
  config:
    import:
      - classpath:/yml/application-secret.yml
      - classpath:/yml/application-local.yml
      - classpath:/yml/application-dev.yml

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    group:
      local:
        - secret # local + secret
      dev:
        - secret
